export const ON_AUTH_META_SET_START = "ON_AUTH_META_SET_START";
export const ON_AUTH_META_SET_SUCCESS = "ON_AUTH_META_SET_SUCCESS";
export const ON_AUTH_META_SET_FAIL = "ON_AUTH_META_SET_FAIL";

export const ON_AUTH_LOGOUT = "ON_AUTH_LOGOUT";
