export const CALCULATE_TOTAL_SPENT_SUCCESS = "CALCULATE_TOTAL_SPENT_SUCCESS";
export const CALCULATE_TOTAL_SPENT_START = "CALCULATE_TOTAL_SPENT_START";

export const INITIAL_BASE_CURRENCY_SET_SUCCESS =
  "INITIAL_BASE_CURRENCY_SET_SUCCESS";
export const BASE_CURRENCY_SET = "BASE_CURRENCY_SET";

export const BASE_CURRENCY_UPDATE_SUCCESS = "BASE_CURRENCY_UPDATE_SUCCESS";
