export const ON_EXPENSES_DELETE_START = "ON_EXPENSES_DELETE_START";
export const ON_EXPENSES_DELETE_SUCCESS = "ON_EXPENSES_DELETE_SUCCESS";
export const ON_EXPENSES_DELETE_FAIL = "ON_EXPENSES_DELETE_FAIL";

