export const ON_ADD_EXPENSE_SUCCESS = "ON_ADD_EXPENSE_SUCCESS";
export const ON_ADD_EXPENSE_FAIL = "ON_ADD_EXPENSE_FAIL";

export const CALCULATE_TOTAL_SPENT_SUCCESS = "CALCULATE_TOTAL_SPENT_SUCCESS";
export const CALCULATE_TOTAL_SPENT_START = "CALCULATE_TOTAL_SPENT_START";

export const INITIAL_BASE_CURRENCY_SET_SUCCESS =
  "INITIAL_BASE_CURRENCY_SET_SUCCESS";
export const BASE_CURRENCY_SET = "BASE_CURRENCY_SET";

export const BASE_CURRENCY_UPDATE_SUCCESS = "BASE_CURRENCY_UPDATE_SUCCESS";

export const ON_DELETE_EXPENSES_SUCCESS = "ON_DELETE_EXPENSES_SUCCESS";
export const ON_DELETE_EXPENSES_FAIL = "ON_DELETE_EXPENSES_FAIL";

export const ON_FETCH_EXPENSES_SUCCESS = "ON_FETCH_EXPENSES_SUCCESS";
export const ON_FETCH_EXPENSES_FAIL = "ON_FETCH_EXPENSES_FAIL";

export const ON_UPDATE_EXPENSES_SUCCESS = "ON_UPDATE_EXPENSES_SUCCESS";
export const ON_UPDATE_EXPENSES_FAIL = "ON_UPDATE_EXPENSES_FAIL";

export const ON_ACTION_FAIL = "ON_ACTION_FAIL";
export const ON_ACTION_START = "ON_ACTION_START";
