export const SHOW_ADD_EXPENSE_FORM = "SHOW_ADD_EXPENSE_FORM";
export const HIDE_ADD_EXPENSE_FORM = "HIDE_ADD_EXPENSE_FORM";

export const FETCH_EXPENSES_SUCCESS = "FETCH_EXPENSES_SUCCESS";

export const CLEAR_EXPENSES = "CLEAR_EXPENSES";
