export const CHANGE_EXPENSE_LISTS_SUCCESS = "CHANGE_EXPENSE_LISTS_SUCCESS";
export const SELECT_EXPENSE_LIST_SUCCESS = "SELECT_EXPENSE_LIST_SUCCESS";

export const SHOW_ADD_EXPENSE_LIST_FORM = "SHOW_ADD_EXPENSE_LIST_FORM";
export const HIDE_ADD_EXPENSE_LIST_FORM = "HIDE_ADD_EXPENSE_LIST_FORM";

export const UPDATE_EXPENSE_LIST_SUCCESS = "UPDATE_EXPENSE_LIST_SUCCESS";
