export const ON_EXPENSE_ADD_START = "ON_EXPENSE_ADD_START";
export const ON_EXPENSE_ADD_SUCCESS = "ON_EXPENSE_ADD_SUCCESS";
export const ON_EXPENSE_ADD_FAIL = "ON_EXPENSE_ADD_FAIL";

export const CALCULATE_TOTAL_SPENT_SUCCESS = "CALCULATE_TOTAL_SPENT_SUCCESS";
export const CALCULATE_TOTAL_SPENT_START = "CALCULATE_TOTAL_SPENT_START";

export const INITIAL_BASE_CURRENCY_SET_SUCCESS =
  "INITIAL_BASE_CURRENCY_SET_SUCCESS";
export const BASE_CURRENCY_SET = "BASE_CURRENCY_SET";

export const BASE_CURRENCY_UPDATE_SUCCESS = "BASE_CURRENCY_UPDATE_SUCCESS";

export const ON_EXPENSES_DELETE_START = "ON_EXPENSES_DELETE_START";
export const ON_EXPENSES_DELETE_SUCCESS = "ON_EXPENSES_DELETE_SUCCESS";
export const ON_EXPENSES_DELETE_FAIL = "ON_EXPENSES_DELETE_FAIL";

export const ON_EXPENSES_FETCH_START = "ON_EXPENSES_FETCH_START";
export const ON_EXPENSES_FETCH_SUCCESS = "ON_EXPENSES_FETCH_SUCCESS";
export const ON_EXPENSES_FETCH_FAIL = "ON_EXPENSES_FETCH_FAIL";

export const ON_EXPENSES_UPDATE_START = "ON_EXPENSES_UPDATE_START";
export const ON_EXPENSES_UPDATE_SUCCESS = "ON_EXPENSES_UPDATE_SUCCESS";
export const ON_EXPENSES_UPDATE_FAIL = "ON_EXPENSES_UPDATE_FAIL";
export const ON_EXPENSES_UPDATE_INIT = "ON_EXPENSES_UPDATE_INIT";
