export const ON_EXPENSES_FETCH_START = "ON_EXPENSES_FETCH_START";
export const ON_EXPENSES_FETCH_SUCCESS = "ON_EXPENSES_FETCH_SUCCESS";
export const ON_EXPENSES_FETCH_FAIL = "ON_EXPENSES_FETCH_FAIL";

