export const CHANGE_GROUP_LISTS_SUCCESS = "CHANGE_GROUP_LISTS_SUCCESS";
export const SELECT_GROUP_LIST_SUCCESS = "SELECT_GROUP_LIST_SUCCESS";

export const SHOW_ADD_GROUP_LIST_FORM = "SHOW_ADD_GROUP_LIST_FORM";
export const HIDE_ADD_GROUP_LIST_FORM = "HIDE_ADD_GROUP_LIST_FORM";

export const UPDATE_GROUP_LIST_SUCCESS = "UPDATE_GROUP_LIST_SUCCESS";

export const CLEAR_SELECTED_GROUP_LIST = "CLEAR_SELECTED_GROUP_LIST";
