export const SUCCESS_NOTIFICATION = "SUCCESS_NOTIFICATION";
export const ERROR_NOTIFICATION = "ERROR_NOTIFICATION";

export const CLEAR_ALL_NOTIFICATIONS = "CLEAR_ALL_NOTIFICATIONS";
export const CLEAR_SUCCESS_NOTIFICATION = "CLEAR_SUCCESS_NOTIFICATION";
export const CLEAR_ERROR_NOTIFICATION = "CLEAR_ERROR_NOTIFICATION";
