export const ON_EXPENSES_UPDATE_START = "ON_EXPENSES_UPDATE_START";
export const ON_EXPENSES_UPDATE_SUCCESS = "ON_EXPENSES_UPDATE_SUCCESS";
export const ON_EXPENSES_UPDATE_FAIL = "ON_EXPENSES_UPDATE_FAIL";

